Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-04, with the labels that each got.

#118 Fix 'load constant' and other 500 errors
  Gemfile
  app/models/ability.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  app/presenters/bulk_exports_presenter.rb
  lib/defra_ruby/exporters/registration_export_service.rb
Labels: bug, housekeeping

#120 Update to support last email cache feature
  Gemfile.lock
  config/initializers/waste_exemptions_engine.rb
Labels: enhancement

#122 Fix data exports accessibility issues
  app/presenters/bulk_exports_presenter.rb
  app/views/bulk_exports/show.html.erb
  config/initializers/time_formats.rb
  config/locales/bulk_exports.en.yml
  spec/requests/bulk_exports_spec.rb
Labels: bug

#124 Fix :month_year date formatting
  config/initializers/time_formats.rb
Labels: bug

#119 Add ability to deregister a whole registration
  app/assets/stylesheets/partials/_resource_details.scss
  app/controllers/deregister_exemptions_controller.rb
  app/controllers/deregister_registrations_controller.rb
  app/forms/deregister_exemptions_form.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/models/waste_exemptions_engine/registration.rb
  app/presenters/deregistrations_presenter.rb
  app/services/deregistration_service.rb
  app/views/deregister_exemptions/new.html.erb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  config/locales/forms/deregister_exemptions.en.yml
  config/routes.rb
  spec/factories/registration.rb
  spec/helpers/action_links_helper_spec.rb
  spec/models/registration_spec.rb
  spec/requests/deregister_exemptions_forms_spec.rb
  spec/services/deregistration_service_spec.rb
Labels: enhancement

#129 Integrate exporters gem
  Gemfile
  Gemfile.lock
  app/presenters/bulk_exports_presenter.rb
  config/initializers/defra_ruby_exporters.rb
  lib/defra_ruby/exporters/bulk_export_file.rb
  lib/defra_ruby/exporters/configuration.rb
  lib/defra_ruby/exporters/helpers/date_range.rb
  lib/defra_ruby/exporters/registration_bulk_export_report.rb
  lib/defra_ruby/exporters/registration_epr_export_report.rb
  lib/defra_ruby/exporters/registration_export_service.rb
  lib/tasks/exporters.rake
  spec/cassettes/save_bulk_export_to_s3.yml
  spec/defra_ruby/exporters/configuration_spec.rb
  spec/defra_ruby/exporters/helpers/date_range_spec.rb
  spec/defra_ruby/exporters/registration_bulk_export_report_spec.rb
  spec/defra_ruby/exporters/registration_epr_export_report_spec.rb
  spec/defra_ruby/exporters/registration_export_service_spec.rb
  spec/requests/bulk_exports_spec.rb
Labels: housekeeping

#130 Expose confirmation letter
  Gemfile
  Gemfile.lock
  app/assets/stylesheets/confirmation_letter.css
  app/assets/stylesheets/confirmation_letter/reset.css
  app/assets/stylesheets/confirmation_letter/wel_styles.css
  app/controllers/confirmation_letter_controller.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/presenters/confirmation_letter_presenter.rb
  app/views/confirmation_letter/_letter_section.html.erb
  app/views/confirmation_letter/show.html.erb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  config/initializers/assets.rb
  config/initializers/wicked_pdf.rb
  config/locales/confirmation_letters.en.yml
  config/routes.rb
  spec/factories/registration.rb
  spec/models/registration_exemption_spec.rb
  spec/requests/confirmation_letter_spec.rb
Labels: enhancement

#148 Remove byebug and swap it with pry-byebug
  Gemfile
  Gemfile.lock
  spec/spec_helper.rb
Labels: housekeeping

#149 Update README.md
  README.md
Labels: housekeeping

#147 Add test coverage for correct handling of 404 errors.
  spec/requests/page_not_found_spec.rb
  spec/support/error_responses_helper.rb
Labels: bug

#141 Use NewRegistration instead of TransientRegistration when appropriate
  Gemfile.lock
  app/controllers/new_registrations_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/dashboards_helper.rb
  app/models/ability.rb
  app/models/waste_exemptions_engine/new_registration.rb
  app/services/search_service.rb
  app/views/dashboards/index.html.erb
  app/views/new_registrations/show.html.erb
  config/locales/dashboards.en.yml
  config/locales/new_registrations.en.yml
  config/routes.rb
  db/schema.rb
  spec/factories/new_registration.rb
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/dashboards_helper_spec.rb
  spec/helpers/registrations_helper_spec.rb
  spec/models/ability_spec.rb
  spec/models/new_registration_spec.rb
  spec/requests/new_registrations_spec.rb
  spec/services/search_service_spec.rb
  spec/support/shared_examples/abilities/admin_agent_examples.rb
  spec/support/shared_examples/abilities/below_admin_agent_examples.rb
  spec/support/shared_examples/abilities/data_agent_examples.rb
Labels: housekeeping

#142 Set up edit links in back office
  Gemfile.lock
  app/helpers/action_links_helper.rb
  app/helpers/waste_exemptions_engine/edit_helper.rb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  spec/factories/edit_registration.rb
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/waste_exemptions_engine/edit_helper_spec.rb
Labels: enhancement

#151 Fix EditHelper inheritance and overriding
  app/helpers/edit_helper.rb
  app/helpers/waste_exemptions_engine/edit_helper.rb
  spec/helpers/edit_helper_spec.rb
  spec/helpers/waste_exemptions_engine/edit_helper_spec.rb
Labels: bug
