Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-10, with the labels that each got.

#436 Add with_postcode to x & y lookup job scope
  lib/tasks/lookups.rake
  spec/lib/tasks/lookups_spec.rb
Labels: bug

#447 Update lookup rake tasks to use new engine services
  Gemfile.lock
  app/services/update_area_service.rb
  app/services/update_easting_and_northing_service.rb
  lib/tasks/lookups.rake
  lib/timed_service_runner.rb
  spec/cassettes/valid_area_lookup.yml
  spec/cassettes/valid_postcode_lookup.yml
  spec/lib/tasks/lookups_spec.rb
  spec/services/update_area_service_spec.rb
  spec/services/update_easting_and_northing_service_spec.rb
Labels: housekeeping

#443 Fix travis link in README
  README.md
Labels: housekeeping

#455 Exclude NCCC postcodes from automated renewal process
  app/models/waste_exemptions_engine/address.rb
  app/models/waste_exemptions_engine/registration.rb
  app/services/renewal_reminder_service_base.rb
  spec/models/address_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/services/first_renewal_reminder_service_spec.rb
  spec/services/second_renewal_reminder_service_spec.rb
Labels: enhancement
