Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-08, with the labels that each got.

#293 Add configs for generating and decoding a renew JWT token
  .env.example
  Gemfile.lock
  config/application.rb
Labels: enhancement

#298 Add schema changes
  db/schema.rb
Labels: enhancement

#300 Update schema - Drop reference index on transient registrations
  db/schema.rb
Labels: enhancement

#305 Update token generation in renew email
  Gemfile.lock
  app/mailers/renewal_reminder_mailer.rb
Labels: housekeeping

#306 Use ENV variable to setup magic link feature toggle
  config/feature_toggles.yml
Labels: enhancement

#308 Add EA logo to renew email
  app/assets/images/logo_ea_color.png
  app/helpers/mailer_helper.rb
  app/views/renewal_reminder_mailer/first_renew_with_magic_link_email.html.erb
Labels: enhancement

#311 Update schema
  db/schema.rb
Labels: enhancement

#316 Add renew link in back office dashboard
  .env.example
  app/controllers/ad_privacy_policy_controller.rb
  app/controllers/renews_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/ad_privacy_policy_helper.rb
  app/models/ability.rb
  app/models/waste_exemptions_engine/registration.rb
  app/views/ad_privacy_policy/show.html.erb
  app/views/shared/_search_result.html.erb
  config/application.rb
  config/locales/partials/search_result.en.yml
  config/routes.rb
  spec/factories/renewing_registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/requests/renews_spec.rb
Labels: enhancement

#318 Add renew link in resource details page
  app/views/shared/_resource_details.html.erb
  config/locales/partials/resource_details.en.yml
Labels: enhancement

#322 Tell search engines not to index app
  public/robots.txt
Labels: enhancement

#324 Add anonymise emails rake task
  lib/tasks/email.rake
Labels: enhancement

#326 Update magic link email text
  config/locales/mailers/renewal_reminder_email.en.yml
  spec/mailers/renewal_mailer_spec.rb
Labels: enhancement

#327 Add ability to custom-parse attribute on Boxi serializer
  app/models/reports/boxi/addresses_serializer.rb
  app/models/reports/boxi/base_serializer.rb
  app/models/reports/boxi/registration_exemptions_serializer.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
  spec/models/reports/boxi/registration_exemptions_serializer_spec.rb
Labels: bug

#332 Add second email reminder for renewals
  .env.example
  .travis.yml
  app/mailers/renewal_reminder_mailer.rb
  app/models/waste_exemptions_engine/registration.rb
  app/services/first_renewal_reminder_service.rb
  app/services/renewal_reminder_service_base.rb
  app/services/second_renewal_reminder_service.rb
  app/views/renewal_reminder_mailer/second_reminder_email.html.erb
  app/views/renewal_reminder_mailer/second_reminder_email.txt.erb
  config/application.rb
  config/feature_toggles.yml
  config/locales/mailers/renewal_reminder_mailer.en.yml
  config/schedule.rb
  lib/tasks/email.rake
  lib/tasks/one_off/reminders.rake
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/schedule_spec.rb
  spec/services/second_renewal_reminder_service_spec.rb
Labels: enhancement

#334 Refactor email reminders to remove non-magic link
  .env.example
  app/mailers/renewal_reminder_mailer.rb
  app/services/first_renewal_reminder_service.rb
  app/views/renewal_reminder_mailer/first_reminder_email.html.erb
  app/views/renewal_reminder_mailer/first_reminder_email.txt.erb
  app/views/renewal_reminder_mailer/first_renew_with_magic_link_email.html.erb
  app/views/renewal_reminder_mailer/first_renew_with_magic_link_email.txt.erb
  config/feature_toggles.yml
  config/locales/mailers/renewal_reminder_mailer.en.yml
  lib/tasks/one_off/reminders.rake
  spec/mailers/renewal_mailer_spec.rb
  spec/services/first_renewal_reminder_service_spec.rb
  spec/services/second_renewal_reminder_service_spec.rb
Labels: housekeeping

#335 Add links to resend renew email in back office
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_flash_messages.scss
  app/controllers/concerns/can_set_flash_messages.rb
  app/controllers/resend_renewal_email_controller.rb
  app/helpers/action_links_helper.rb
  app/views/dashboards/index.html.erb
  app/views/registrations/show.html.erb
  app/views/shared/_error.html.erb
  app/views/shared/_message.html.erb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  config/locales/partials/resource_details.en.yml
  config/locales/partials/search_result.en.yml
  config/locales/resend_renewal_email.en.yml
  config/routes.rb
  spec/requests/resend_renewal_email_spec.rb
Labels: enhancement

#336 Do not show renew links on not active registrations
  app/helpers/action_links_helper.rb
Labels: enhancement

#342 Don't require active status to display renewal link
  app/helpers/action_links_helper.rb
  spec/helpers/action_links_helper_spec.rb
Labels: bug

#343 Include expired exemptions in renewal emails
  app/mailers/renewal_reminder_mailer.rb
  spec/mailers/renewal_mailer_spec.rb
Labels: enhancement

#347 Do not open renewals in new tab
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
Labels: bug

#350 Add rake task to remove old transient_registrations
  .env.example
  app/services/transient_registration_cleanup_service.rb
  config/application.rb
  lib/tasks/cleanup.rake
  spec/services/transient_registration_cleanup_service_spec.rb
Labels: enhancement

#352 Schedule transient registration cleanup task
  .env.example
  .travis.yml
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#353 Fix cleanup:transient_registrations rake task
  app/services/transient_registration_cleanup_service.rb
  lib/tasks/cleanup.rake
Labels: bug

#349 Make the registration responsible to know if it is renewable
  app/helpers/action_links_helper.rb
  app/models/waste_exemptions_engine/registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: housekeeping

#355 Show an already renewed message when relevant
  app/helpers/action_links_helper.rb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  config/locales/partials/resource_details.en.yml
  config/locales/partials/search_result.en.yml
  spec/helpers/action_links_helper_spec.rb
Labels: enhancement

#356 Add link to renewed from registration in details page
  Gemfile.lock
  app/views/shared/_resource_details.html.erb
  config/locales/partials/resource_details.en.yml
Labels: enhancement

#364 Make the cutoff for cleaning out old records start of day
  app/services/transient_registration_cleanup_service.rb
Labels: bug
