Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-06, with the labels that each got.

#194 Update to include site address area
  app/views/shared/_resource_address.html.erb
  config/locales/partials/resource_address.en.yml
  db/schema.rb
Labels: enhancement

#191 Exemptions Bulk export rake task
  app/models/reports.rb
  app/models/reports/monthly_bulk_serializer.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/presenters/reports/exemption_bulk_report_presenter.rb
  app/services/reports/bulk_export_service.rb
  app/services/reports/monthly_bulk_report_service.rb
  config/initializers/time_formats.rb
  lib/tasks/exemptions_reports.rake
  spec/factories/registration_exemption.rb
  spec/models/reports/monthly_bulk_serializer_spec.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
  spec/services/reports/bulk_export_service_spec.rb
  spec/services/reports/monthly_bulk_report_service_spec.rb
Labels: enhancement

#198 Implement Aws bucket load of report bulk CSV files
  Gemfile
  Gemfile.lock
  app/services/reports/monthly_bulk_report_service.rb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  spec/factories/registration_exemption.rb
  spec/services/reports/monthly_bulk_report_service_spec.rb
Labels: enhancement

#199 Save report generation to the database
  app/models/reports.rb
  app/models/reports/generated_report.rb
  app/services/reports/monthly_bulk_report_service.rb
  spec/services/reports/monthly_bulk_report_service_spec.rb
Labels: enhancement

#201 Monthly Bulk Export - Ensure the database entries are cleared
  app/services/reports/bulk_export_service.rb
  spec/services/reports/bulk_export_service_spec.rb
Labels: enhancement

#204 Set correct TZ timezone
  .travis.yml
Labels: enhancement

#203 Add links to AWS bulk export files
  app/models/reports/generated_report.rb
  app/models/reports/monthly_bulk_serializer.rb
  app/presenters/bulk_exports_presenter.rb
  app/presenters/reports/exemption_bulk_report_presenter.rb
  app/services/reports/monthly_bulk_report_service.rb
  spec/factories/reports/generated_report.rb
  spec/requests/bulk_exports_spec.rb
  spec/services/reports/monthly_bulk_report_service_spec.rb
Labels: enhancement

#207 Update reports namespace to be consistent
  lib/tasks/reports.rake
Labels: housekeeping

#208 Update schedule to run the new export rake task
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#209 Use the new Reports::GeneratedReport to deal with reports permissions
  app/controllers/bulk_exports_controller.rb
  app/models/ability.rb
  app/models/reports/generated_report.rb
  app/views/layouts/application.html.erb
  spec/support/shared_examples/abilities/data_agent_examples.rb
Labels: enhancement

#210 Use application configs to access ENV variables
  app/models/reports/monthly_bulk_serializer.rb
  config/application.rb
Labels: housekeeping

#212 Remove change your password link from the back office dashboard
  app/views/dashboards/index.html.erb
  config/locales/dashboards.en.yml
Labels: enhancement

#213 Return blank site address when location is by grid reference
  app/presenters/reports/exemption_bulk_report_presenter.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Labels: bug

#218 Downgrade Postgres version to 9.6
  .travis.yml
Labels: bug

#219 Change return field for assisted mode
  app/presenters/reports/exemption_bulk_report_presenter.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Labels: enhancement

#220 Remove operator from address data bulk export
  app/presenters/reports/exemption_bulk_report_presenter.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Labels: enhancement

#223 Remove VCR and its configuration
  Gemfile
  Gemfile.lock
  spec/cassettes/clear_bulk_export_s3_bucket.yml
  spec/cassettes/get_bulk_export_s3_bucket.yml
  spec/cassettes/save_epr_export_to_s3.yml
  spec/schedule_spec.rb
  spec/services/reports/bulk_export_service_spec.rb
  spec/spec_helper.rb
  spec/support/helpers/vcr.rb
  spec/support/vcr.rb
Labels: housekeeping

#222 Implement EPR exports with new DefraRubyAws gem
  app/models/reports/base_serializer.rb
  app/models/reports/epr_serializer.rb
  app/models/reports/monthly_bulk_serializer.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/presenters/reports/exemption_epr_report_presenter.rb
  app/services/reports/concerns/can_load_file_to_aws.rb
  app/services/reports/epr_export_service.rb
  app/services/reports/monthly_bulk_report_service.rb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  config/schedule.rb
  lib/tasks/reports.rake
  spec/factories/registration_exemption.rb
  spec/presenters/reports/exemption_epr_report_presenter_spec.rb
  spec/schedule_spec.rb
  spec/services/reports/epr_export_service_spec.rb
  spec/services/reports/monthly_bulk_report_service_spec.rb
Labels: enhancement

#224 Remove defra_ruby_exporters gem and its configuration
  .env.example
  .travis.yml
  Gemfile
  Gemfile.lock
  app/presenters/bulk_exports_presenter.rb
  config/application.rb
  config/initializers/defra_ruby_exporters.rb
  lib/defra_ruby/exporters/bulk_export_file.rb
  lib/defra_ruby/exporters/registration_bulk_export_report.rb
  lib/defra_ruby/exporters/registration_epr_export_report.rb
  spec/defra_ruby/exporters/registration_bulk_export_report_spec.rb
  spec/defra_ruby/exporters/registration_epr_export_report_spec.rb
  spec/requests/bulk_exports_spec.rb
Labels: housekeeping

#234 Require `csv` library in reports base serializer
  app/models/reports/base_serializer.rb
Labels: bug

#235 Fix defra_ruby_aws gem name
  Gemfile
  Gemfile.lock
Labels: housekeeping

#239 Use registration state when displaying registrations in the dashboard
  app/helpers/dashboards_helper.rb
  config/locales/partials/search_result.en.yml
  spec/helpers/dashboards_helper_spec.rb
Labels: bug

#229 Build first reminder email
  app/mailers/renewal_reminder_mailer.rb
  app/views/renewal_reminder_mailer/first_reminder_email.html.erb
  app/views/renewal_reminder_mailer/first_reminder_email.txt.erb
  config/locales/mailers/renewal_reminder_email.en.yml
  lib/tasks/one_off/reminders.rake
  spec/factories/address.rb
  spec/factories/registration.rb
  spec/mailers/renewal_mailer_spec.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Labels: enhancement

#241 Fix HTML W3C issues
  app/views/deregister_exemptions/new.html.erb
  app/views/layouts/application.html.erb
  app/views/shared/_resource_address.html.erb
  app/views/shared/_resource_details.html.erb
Labels: bug

#242 Make sure Registration states are returned in order of importance
  app/models/waste_exemptions_engine/registration.rb
  spec/factories/registration_exemption.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
Labels: bug

#244 Update bulk exporter schedule to be daily
  .env.example
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#243 Add rake task to send first email reminder for renewals
  .env.example
  app/services/first_renewal_reminder_service.rb
  config/application.rb
  lib/tasks/email.rake
  spec/services/first_renewal_reminder_service_spec.rb
Labels: enhancement

#245 Schedule first email reminder job
  .env.example
  .travis.yml
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#246 Rename email reminders task to include `first`
  config/schedule.rb
  lib/tasks/email.rake
  spec/schedule_spec.rb
Labels: housekeeping
