Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-07, with the labels that each got.

#247 Add missing mailto to link
  app/views/shared/_resource_details.html.erb
Labels: bug

#251 Fix bug on first day of the month bulk report generation
  app/services/reports/bulk_export_service.rb
Labels: bug

#248 Fix error when in confirmation letter for expired
  app/presenters/confirmation_letter_presenter.rb
  config/locales/confirmation_letters.en.yml
  spec/presenters/confirmation_letter_presenter_spec.rb
Labels: bug

#253 Update schema.rb
  db/schema.rb
Labels: bug

#252 Do not seed exemptions in the test suite, use factories instead
  spec/factories/new_registration.rb
  spec/factories/registration.rb
  spec/models/registration_exemption_spec.rb
  spec/models/reports/monthly_bulk_serializer_spec.rb
  spec/rails_helper.rb
Labels: housekeeping

#254 Add feature toggle check for first email reminder
  Gemfile.lock
  config/feature_toggles.yml
  lib/tasks/email.rake
Labels: enhancement

#260 Fix minor bugs in first email reminder
  app/views/renewal_reminder_mailer/first_reminder_email.html.erb
Labels: bug

#255 Add rake task to set the status of expired registration exemptions
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/services/expired_registrations_service.rb
  lib/tasks/expire_registration.rake
  spec/services/expired_registrations_service_spec.rb
Labels: enhancement

#258 Break long emails onto multiple lines instead of overflowing
  app/assets/stylesheets/partials/_resource_details.scss
  app/views/shared/_resource_details.html.erb
Labels: bug

#263 Include polyfill for old browsers support
  Gemfile
  Gemfile.lock
  app/assets/javascripts/application.js
  app/views/layouts/application.html.erb
Labels: enhancement

#256 Schedule the registration exemptions expiry job to run daily
  .env.example
  .travis.yml
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#266 Attach logo to email instead of linking to gov.uk
  app/helpers/mailer_helper.rb
  app/mailers/renewal_reminder_mailer.rb
  app/views/renewal_reminder_mailer/first_reminder_email.html.erb
  spec/mailers/renewal_mailer_spec.rb
Labels: enhancement

#265 Add privacy policy for Assited Digital
  app/controllers/ad_privacy_policy_controller.rb
  app/helpers/ad_privacy_policy_helper.rb
  app/views/ad_privacy_policy/show.html.erb
  app/views/dashboards/index.html.erb
  config/locales/ad_privacy_policy.en.yml
  config/routes.rb
  spec/requests/ad_privacy_policy_spec.rb
Labels: enhancement

#270 Update privacy policy
  app/views/pages/privacy.html.erb
Labels: bug

#272 Use id instead of reference when dealing with in progress registrations
  Gemfile.lock
  app/helpers/action_links_helper.rb
  app/views/new_registrations/show.html.erb
  config/locales/new_registrations.en.yml
  config/routes.rb
  spec/factories/new_registration.rb
  spec/helpers/action_links_helper_spec.rb
  spec/presenters/reports/exemption_epr_report_presenter_spec.rb
  spec/requests/new_registrations_spec.rb
  spec/services/search_service_spec.rb
Labels: housekeeping

#274 Use id instead of reference to find the correct new registration
  app/controllers/new_registrations_controller.rb
Labels: bug

#276 Generate Boxi report CSV files for AWS export
  .env.example
  .travis.yml
  Gemfile
  Gemfile.lock
  app/models/boxi_export/addresses_serializer.rb
  app/models/boxi_export/base_serializer.rb
  app/models/boxi_export/exemptions_serializer.rb
  app/models/boxi_export/people_serializer.rb
  app/models/boxi_export/registration_exemptions_serializer.rb
  app/models/boxi_export/registrations_serializer.rb
  app/services/boxi_export/generator_service.rb
  app/services/concerns/can_load_file_to_aws.rb
  app/services/reports/concerns/can_load_file_to_aws.rb
  app/services/reports/epr_export_service.rb
  app/services/reports/monthly_bulk_report_service.rb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  lib/tasks/boxi_export.rake
  spec/models/boxi_export/addresses_serializer_spec.rb
  spec/models/boxi_export/base_serializer_spec.rb
  spec/models/boxi_export/exemptions_serializer_spec.rb
  spec/models/boxi_export/people_serializer_spec.rb
  spec/models/boxi_export/registration_exemptions_serializer_spec.rb
  spec/models/boxi_export/registrations_serializer_spec.rb
  spec/services/boxi_export/generator_service_spec.rb
  spec/support/shared_examples/a_boxi_serializer.rb
Labels: enhancement

#277 Schedule boxi generation service job
  .env.example
  .travis.yml
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#280 Prevent exports to fail if a required address is missing
  app/presenters/reports/exemption_bulk_report_presenter.rb
  app/presenters/reports/exemption_epr_report_presenter.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
  spec/presenters/reports/exemption_epr_report_presenter_spec.rb
Labels: enhancement

#283 Add feature toggle on Boxi export
  config/feature_toggles.yml
  lib/tasks/boxi_export.rake
Labels: enhancement

#281 Activate first email reminder feature
  config/feature_toggles.yml
Labels: enhancement

#286 Close Airbrake to execute async promises
  lib/tasks/boxi_export.rake
  lib/tasks/email.rake
  lib/tasks/expire_registration.rake
  lib/tasks/reports.rake
Labels: bug

#287 Move BOXI export to reports namespace
  .travis.yml
  app/models/boxi_export/addresses_serializer.rb
  app/models/boxi_export/base_serializer.rb
  app/models/boxi_export/exemptions_serializer.rb
  app/models/boxi_export/people_serializer.rb
  app/models/boxi_export/registration_exemptions_serializer.rb
  app/models/boxi_export/registrations_serializer.rb
  app/models/reports/base_serializer.rb
  app/models/reports/boxi/addresses_serializer.rb
  app/models/reports/boxi/base_serializer.rb
  app/models/reports/boxi/exemptions_serializer.rb
  app/models/reports/boxi/people_serializer.rb
  app/models/reports/boxi/registration_exemptions_serializer.rb
  app/models/reports/boxi/registrations_serializer.rb
  app/services/reports/boxi_export_service.rb
  config/application.rb
  config/schedule.rb
  lib/tasks/boxi_export.rake
  lib/tasks/reports.rake
  spec/models/boxi_export/addresses_serializer_spec.rb
  spec/models/boxi_export/base_serializer_spec.rb
  spec/models/boxi_export/exemptions_serializer_spec.rb
  spec/models/boxi_export/people_serializer_spec.rb
  spec/models/boxi_export/registration_exemptions_serializer_spec.rb
  spec/models/boxi_export/registrations_serializer_spec.rb
  spec/models/reports/boxi/addresses_serializer_spec.rb
  spec/models/reports/boxi/base_serializer_spec.rb
  spec/models/reports/boxi/exemptions_serializer_spec.rb
  spec/models/reports/boxi/people_serializer_spec.rb
  spec/models/reports/boxi/registration_exemptions_serializer_spec.rb
  spec/models/reports/boxi/registrations_serializer_spec.rb
  spec/schedule_spec.rb
  spec/services/reports/boxi_export_service_spec.rb
Labels: housekeeping

#292 Update .env.example post BOXI changes
  .env.example
Labels: housekeeping
