Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-05, with the labels that each got.

#152 Inherit SCSS from engine
  app/assets/stylesheets/application.scss
Labels: bug

#155 Revert "Add test coverage for correct handling of 404 errors."
  spec/requests/page_not_found_spec.rb
  spec/support/error_responses_helper.rb
Labels: housekeeping

#153 Configure editing permissions
  app/controllers/application_controller.rb
  app/controllers/concerns/.keep
  app/controllers/concerns/permission_checks.rb
  app/helpers/action_links_helper.rb
  config/initializers/waste_exemptions_engine.rb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/engine_spec.rb
Labels: enhancement

#159 Fix bug on show of New registration objects
  app/models/concerns/can_be_ordered_by_state_and_exemption_id.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/models/waste_exemptions_engine/transient_registration_exemption.rb
  spec/factories/new_registration.rb
Labels: bug

#163 Refactor the code to use the service checker permission
  Gemfile.lock
  app/controllers/application_controller.rb
  app/controllers/concerns/permission_checks.rb
  app/services/waste_exemptions_engine/edit_permission_checker_service.rb
Labels: bug

#166 Set the config timezone to be London rather than UTC
  config/application.rb
Labels: bug

#135 Fix issues found with confirmation letter
  .travis.yml
  Gemfile
  Gemfile.lock
  app/assets/images/.keep
  app/assets/images/logo_ea.png
  app/assets/stylesheets/confirmation_letter.css
  app/assets/stylesheets/confirmation_letter/reset.css
  app/assets/stylesheets/confirmation_letter/wel_styles.css
  app/controllers/confirmation_letter_controller.rb
  app/presenters/base_presenter.rb
  app/presenters/confirmation_letter_presenter.rb
  app/views/confirmation_letter/_letter_section.html.erb
  app/views/confirmation_letter/show.html.erb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  config/initializers/time_formats.rb
  config/initializers/wicked_pdf.rb
  config/locales/confirmation_letters.en.yml
  script/wkhtmltopdf.sh
  spec/factories/address.rb
  spec/factories/exemption.rb
  spec/factories/person.rb
  spec/factories/registration.rb
  spec/factories/registration_exemption.rb
  spec/models/address_spec.rb
  spec/models/registration_spec.rb
  spec/presenters/confirmation_letter_presenter_spec.rb
  spec/requests/confirmation_letter_spec.rb
Labels: bug

#172 Require defra-ruby-exporters gem before Rails tasks are loaded
  Rakefile
Labels: bug

#176 Add operator details in the registration view and change label
  app/views/shared/_resource_address.html.erb
  app/views/shared/_resource_details.html.erb
  config/locales/partials/resource_address.en.yml
  config/locales/partials/resource_details.en.yml
  config/locales/partials/search_result.en.yml
Labels: enhancement

#180 Rename deregistered_on to deregistered_at
  Gemfile.lock
  app/models/concerns/can_deactivate_exemption.rb
  app/models/waste_exemptions_engine/registration.rb
  app/presenters/confirmation_letter_presenter.rb
  db/schema.rb
  lib/defra_ruby/exporters/registration_bulk_export_report.rb
  spec/factories/registration_exemption.rb
  spec/models/registration_exemption_spec.rb
  spec/models/registration_spec.rb
  spec/services/deregistration_service_spec.rb
Labels: housekeeping

#185 Fix test fail when run at midnight BST
  spec/models/registration_spec.rb
Labels: bug

#182 Remove wickedpdf gem and configs
  Gemfile
  Gemfile.lock
  config/initializers/wicked_pdf.rb
  script/wkhtmltopdf.sh
Labels: bug

#188 Save session token change to database
  app/models/user.rb
  spec/requests/sessions_spec.rb
Labels: bug

#189 Fix WEX data exports
  config/initializers/defra_ruby_exporters.rb
Labels: bug
