Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-03, with the labels that each got.

#70 Remove 'change AD level' link from search results
  app/views/shared/_search_result.html.erb
  config/locales/partials/search_result.en.yml
Labels: bug

#71 Deal with excess whitespace when searching
  app/services/search_service.rb
  spec/services/search_service_spec.rb
Labels: bug

#72 Add fieldset for search filters
  app/views/dashboards/index.html.erb
  config/locales/dashboards.en.yml
Labels: bug

#74 Remove site address from results if not yet added
  app/views/shared/_search_result.html.erb
  config/locales/partials/search_result.en.yml
Labels: bug

#56 Add registration details page
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_dashboard.scss
  app/assets/stylesheets/partials/_resource_details.scss
  app/assets/stylesheets/partials/_tags.scss
  app/controllers/registrations_controller.rb
  app/controllers/transient_registrations_controller.rb
  app/helpers/dashboards_helper.rb
  app/helpers/registrations_helper.rb
  app/models/ability.rb
  app/views/registrations/show.html.erb
  app/views/shared/_resource_address.html.erb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_resource_exemptions_list.html.erb
  app/views/shared/_resource_people_list.html.erb
  app/views/shared/_search_result.html.erb
  app/views/transient_registrations/show.html.erb
  config/locales/partials/resource_address.en.yml
  config/locales/partials/resource_details.en.yml
  config/locales/partials/resource_exemptions_list.en.yml
  config/locales/partials/search_result.en.yml
  config/locales/registrations.en.yml
  config/locales/transient_registrations.en.yml
  config/routes.rb
  spec/helpers/dashboards_helper_spec.rb
  spec/helpers/registrations_helper_spec.rb
  spec/requests/dashboards_spec.rb
  spec/requests/registrations_spec.rb
  spec/requests/transient_registrations_spec.rb
  spec/support/shared_examples/abilities/data_agent_examples.rb
Labels: enhancement

#79 Unlock Rails version
  Gemfile
  Gemfile.lock
Labels: housekeeping

#75 Implement PaperTrail for auditing
  Gemfile
  Gemfile.lock
  app/controllers/application_controller.rb
  app/models/user.rb
  db/migrate/20190311150953_create_versions.rb
  db/schema.rb
  spec/models/user_spec.rb
  spec/requests/user_roles_spec.rb
  spec/support/paper_trail.rb
Labels: enhancement

#78 Add a root div to results in dashboard
  app/views/dashboards/index.html.erb
Labels: housekeeping

#84 Display dates in human-friendly format
  app/views/shared/_resource_exemptions_list.html.erb
Labels: bug

#91 Remove extra version migration
  Gemfile.lock
  db/migrate/20190311150953_create_versions.rb
Labels: bug

#85 Allow back office users to complete an in-progress registration
  app/controllers/dashboards_controller.rb
  app/controllers/registrations_controller.rb
  app/controllers/transient_registrations_controller.rb
  app/helpers/action_links_helper.rb
  app/helpers/dashboards_helper.rb
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  spec/helpers/action_links_helper_spec.rb
  spec/helpers/dashboards_helper_spec.rb
Labels: enhancement

#92 Set default assistance_mode
  app/views/shared/_resource_details.html.erb
  config/initializers/waste_exemptions_engine.rb
  config/locales/partials/resource_details.en.yml
  db/schema.rb
Labels: enhancement

#69 Create public register exporter
  .env.example
  .gitignore
  .travis.yml
  Gemfile
  Gemfile.lock
  config/application.rb
  config/initializers/defra_ruby_exporters.rb
  config/schedule.rb
  lib/defra_ruby/exporters/registration_epr_export_report.rb
  lib/defra_ruby/exporters/registration_export_service.rb
  spec/cassettes/save_epr_export_to_s3.yml
  spec/defra_ruby/exporters/registration_epr_export_report_spec.rb
  spec/defra_ruby/exporters/registration_export_service_spec.rb
  spec/factories/address.rb
  spec/factories/registration.rb
  spec/rails_helper.rb
  spec/schedule_spec.rb
  spec/support/helpers/registrations.rb
  spec/support/helpers/vcr.rb
  spec/support/vcr.rb
Labels: enhancement

#98 Fix error when calling `bundle exec whenever`
  config/initializers/defra_ruby_exporters.rb
  config/schedule.rb
  spec/schedule_spec.rb
Labels: bug

#99 Make whenever cron log output configurable
  .env.example
  .travis.yml
  config/schedule.rb
  spec/schedule_spec.rb
Labels: bug

#100 Fix Airbrake for the dev environment
  config/initializers/airbrake.rb
Labels: bug

#104 Refactor the whenever schedule to use Rake
  config/schedule.rb
  lib/defra_ruby/exporters/registration_export_service.rb
  lib/tasks/exporters.rake
  spec/defra_ruby/exporters/registration_export_service_spec.rb
  spec/schedule_spec.rb
Labels: bug, housekeeping

#113 Update schema to include deregistered_on
  db/schema.rb
Labels: housekeeping

#105 Add bulk export functionality to DefraRuby::Exporters
  .env.example
  .travis.yml
  app/controllers/bulk_exports_controller.rb
  app/models/ability.rb
  app/presenters/bulk_exports_presenter.rb
  app/views/bulk_exports/show.html.erb
  app/views/layouts/application.html.erb
  config/initializers/defra_ruby_exporters.rb
  config/locales/bulk_exports.en.yml
  config/locales/en.yml
  config/routes.rb
  config/schedule.rb
  db/migrate/20190327134526_create_defra_ruby_exporters_bulk_export_files.rb
  db/schema.rb
  lib/defra_ruby/exporters/bulk_export_file.rb
  lib/defra_ruby/exporters/configuration.rb
  lib/defra_ruby/exporters/helpers/date_range.rb
  lib/defra_ruby/exporters/registration_bulk_export_report.rb
  lib/defra_ruby/exporters/registration_export_service.rb
  lib/tasks/exporters.rake
  spec/cassettes/clear_bulk_export_s3_bucket.yml
  spec/cassettes/get_bulk_export_s3_bucket.yml
  spec/cassettes/save_bulk_export_to_s3.yml
  spec/cassettes/save_epr_export_to_s3.yml
  spec/defra_ruby/exporters/configuration_spec.rb
  spec/defra_ruby/exporters/helpers/date_range_spec.rb
  spec/defra_ruby/exporters/registration_bulk_export_report_spec.rb
  spec/defra_ruby/exporters/registration_epr_export_report_spec.rb
  spec/defra_ruby/exporters/registration_export_service_spec.rb
  spec/requests/bulk_exports_spec.rb
  spec/schedule_spec.rb
  spec/support/helpers/registrations.rb
  spec/support/helpers/vcr.rb
  spec/support/shared_examples/abilities/data_agent_examples.rb
  spec/support/vcr.rb
Labels: enhancement

#90 Support individual exemption deregistration
  Gemfile.lock
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_input.scss
  app/controllers/application_controller.rb
  app/controllers/deregister_exemptions_controller.rb
  app/forms/deregister_exemptions_form.rb
  app/models/ability.rb
  app/models/concerns/waste_exemptions_engine/can_deactivate_exemption.rb
  app/models/user.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  app/services/deregistration_service.rb
  app/validators/deregistration_message_validator.rb
  app/validators/deregistration_state_transition_validator.rb
  app/views/deregister_exemptions/new.html.erb
  app/views/shared/_resource_exemptions_list.html.erb
  config/locales/forms/deregister_exemptions.en.yml
  config/locales/partials/resource_exemptions_list.en.yml
  config/routes.rb
  spec/forms/deregister_exemptions_form_spec.rb
  spec/models/registration_exemption_spec.rb
  spec/requests/deregister_exemptions_forms_spec.rb
  spec/services/deregistration_service_spec.rb
  spec/support/helpers/error_translator.rb
  spec/support/helpers/text_generator.rb
  spec/support/shared_examples/validators/invalid_record.rb
  spec/support/shared_examples/validators/length_validator.rb
  spec/support/shared_examples/validators/presence_validator.rb
  spec/support/shared_examples/validators/selection_validator.rb
  spec/support/shared_examples/validators/valid_record.rb
  spec/support/shared_examples/validators/validator.rb
  spec/validators/deregistration_message_validator_spec.rb
  spec/validators/deregistration_state_transition_validator_spec.rb
Labels: enhancement

#116 Add Bullet and fix unoptimised queries
  Gemfile
  Gemfile.lock
  app/views/shared/_resource_details.html.erb
  config/environments/test.rb
  spec/rails_helper.rb
Labels: housekeeping

#109 Refactor the model concerns namespace
  app/models/concerns/can_be_searched_like_address.rb
  app/models/concerns/can_be_searched_like_person.rb
  app/models/concerns/can_be_searched_like_registration.rb
  app/models/concerns/can_deactivate_exemption.rb
  app/models/concerns/waste_exemptions_engine/can_be_searched_like_address.rb
  app/models/concerns/waste_exemptions_engine/can_be_searched_like_person.rb
  app/models/concerns/waste_exemptions_engine/can_be_searched_like_registration.rb
  app/models/concerns/waste_exemptions_engine/can_deactivate_exemption.rb
Labels: housekeeping
