Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-02, with the labels that each got.

#16 Display regs on dashboard in a useful way
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_dashboard.scss
  app/views/dashboards/index.html.erb
  config/locales/dashboards.en.yml
Labels: enhancement

#19 Add dashboard for user management
  app/controllers/application_controller.rb
  app/controllers/users_controller.rb
  app/views/layouts/application.html.erb
  app/views/users/index.html.erb
  config/locales/en.yml
  config/locales/users.en.yml
  config/routes.rb
  spec/requests/users_spec.rb
Labels: enhancement

#23 Align rspec test setup with WEX engine
  spec/rails_helper.rb
  spec/spec_helper.rb
  spec/support/database_cleaner.rb
  spec/support/factory_bot.rb
  spec/support/simplecov.rb
Labels: housekeeping

#26 Display partner names on separate lines
  app/views/dashboards/index.html.erb
Labels: bug

#27 Add unique IDs to action links on dashboard
  app/views/dashboards/index.html.erb
Labels: housekeeping

#25 Display pagination on registration dashboard
  app/views/dashboards/index.html.erb
Labels: bug

#30 Configure Sendgrid and add rake task to test emails
  .env.example
  app/mailers/.keep
  app/mailers/test_mailer.rb
  app/views/test_mailer/test_email.text.erb
  config/application.rb
  config/environments/development.rb
  config/environments/production.rb
  config/environments/test.rb
  config/initializers/waste_exemptions_engine.rb
  lib/tasks/email.rake
  spec/mailers/test_mailer_spec.rb
Labels: enhancement

#21 Activate and deactivate back office user accounts
  app/controllers/application_controller.rb
  app/controllers/sessions_controller.rb
  app/controllers/user_activations_controller.rb
  app/models/ability.rb
  app/models/user.rb
  app/views/pages/deactivated.html.erb
  app/views/user_activations/activate_form.html.erb
  app/views/user_activations/deactivate_form.html.erb
  app/views/users/index.html.erb
  config/locales/pages/deactivated.en.yml
  config/locales/user_activations.en.yml
  config/locales/users.en.yml
  config/routes.rb
  db/migrate/20190204103029_add_active_to_users.rb
  db/schema.rb
  spec/factories/user.rb
  spec/models/ability_spec.rb
  spec/models/user_spec.rb
  spec/requests/dashboards_spec.rb
  spec/requests/engine_spec.rb
  spec/requests/sessions_spec.rb
  spec/requests/user_activations_spec.rb
  spec/support/shared_examples/abilities/below_system_examples.rb
  spec/support/shared_examples/abilities/data_agent_examples.rb
  spec/support/shared_examples/abilities/system_examples.rb
Labels: enhancement

#35 Add sign-out link to deactivated page
  app/views/pages/deactivated.html.erb
  config/locales/pages/deactivated.en.yml
Labels: enhancement

#33 Invite a new user to the back office
  app/controllers/user_invitations_controller.rb
  app/views/devise/mailer/invitation_instructions.html.erb
  app/views/devise/mailer/invitation_instructions.text.erb
  app/views/user_invitations/edit.html.erb
  app/views/user_invitations/new.html.erb
  app/views/users/index.html.erb
  config/environments/test.rb
  config/initializers/devise.rb
  config/locales/mailers/devise.en.yml
  config/locales/user_invitations.en.yml
  config/locales/users.en.yml
  config/routes.rb
  spec/requests/user_invitations_spec.rb
Labels: enhancement

#38 Make use of airbrake configurable in initializer
  config/initializers/airbrake.rb
Labels: enhancement

#39 Set secret_key_base when run under prod & rake
  config/application.rb
Labels: bug

#44 Update TravisCI badge URL
  README.md
Labels: housekeeping

#45 Force ssl in production environments
  config/environments/production.rb
Labels: enhancement

#52 Change a user's role
  app/controllers/user_roles_controller.rb
  app/models/user.rb
  app/views/shared/_select_role.html.erb
  app/views/user_invitations/new.html.erb
  app/views/user_roles/edit.html.erb
  app/views/users/index.html.erb
  config/locales/en.yml
  config/locales/user_invitations.en.yml
  config/locales/user_roles.en.yml
  config/routes.rb
  spec/models/user_spec.rb
  spec/requests/user_roles_spec.rb
Labels: enhancement

#55 Link to start a new AD registration
  app/views/dashboards/index.html.erb
  config/locales/dashboards.en.yml
  config/locales/en.yml
Labels: enhancement

#47 Add pgreset gem to solve database in use errors
  Gemfile
  Gemfile.lock
Labels: housekeeping

#48 Remove dummy secret key logic in application.rb
  config/application.rb
Labels: housekeeping

#60 Fix people form button styling
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_people.scss
Labels: bug

#61 Block data agents from doing AD registrations
  app/controllers/application_controller.rb
  app/views/dashboards/index.html.erb
  app/views/pages/permission.html.erb
  config/locales/pages/permission.en.yml
  spec/requests/engine_spec.rb
Labels: bug

#62 Search for in-progress new registrations
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_dashboard.scss
  app/assets/stylesheets/partials/_search.scss
  app/controllers/dashboards_controller.rb
  app/helpers/dashboards_helper.rb
  app/models/concerns/.keep
  app/models/concerns/waste_exemptions_engine/can_be_searched_like_address.rb
  app/models/concerns/waste_exemptions_engine/can_be_searched_like_person.rb
  app/models/concerns/waste_exemptions_engine/can_be_searched_like_registration.rb
  app/models/waste_exemptions_engine/address.rb
  app/models/waste_exemptions_engine/person.rb
  app/models/waste_exemptions_engine/registration.rb
  app/models/waste_exemptions_engine/transient_address.rb
  app/models/waste_exemptions_engine/transient_person.rb
  app/models/waste_exemptions_engine/transient_registration.rb
  app/services/search_service.rb
  app/views/dashboards/index.html.erb
  app/views/shared/_search_result.html.erb
  config/locales/dashboards.en.yml
  config/locales/partials/search_result.en.yml
  spec/factories/transient_address.rb
  spec/factories/transient_person.rb
  spec/factories/transient_registration.rb
  spec/helpers/dashboards_helper_spec.rb
  spec/models/transient_address_spec.rb
  spec/models/transient_person_spec.rb
  spec/models/transient_registration_spec.rb
  spec/requests/dashboards_spec.rb
  spec/services/search_service_spec.rb
Labels: enhancement
