Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2019-09, with the labels that each got.

#371 Add link to view renewal letter
  app/views/shared/_resource_details.html.erb
  app/views/shared/_search_result.html.erb
  config/locales/partials/resource_details.en.yml
  config/locales/partials/search_result.en.yml
Labels: enhancement

#374 Don't list revoked and ceased exemptions in renewal letter
  app/presenters/renewal_letter_presenter.rb
  spec/presenters/renewal_letter_presenter_spec.rb
Labels: bug

#375 Don't include ceased/revoked exemptions in 'unlisted exemptions' count
  app/presenters/renewal_letter_presenter.rb
  spec/presenters/renewal_letter_presenter_spec.rb
Labels: bug

#381 Update project following name change
  .travis.yml
  README.md
  config/application.rb
  config/initializers/waste_exemptions_engine.rb
Labels: housekeeping

#383 AD renewal letters bulk generation
  .travis.yml
  app/models/waste_exemptions_engine/ad_renewal_letters_export.rb
  app/services/ad_renewal_letters_export_service.rb
  app/services/renewal_letters_bulk_pdf_service.rb
  app/views/renewal_letter/_renewal_letter_content.html.erb
  app/views/renewal_letter/_styles.html.erb
  app/views/renewal_letter/bulk.html.erb
  app/views/renewal_letter/show.html.erb
  config/application.rb
  config/initializers/defra_ruby_aws.rb
  config/locales/renewal_letter.en.yml
  db/migrate/20190909093455_create_ad_renewal_letters_exports.rb
  db/schema.rb
  lib/tasks/ad_renewal_letters.rake
  spec/factories/registration.rb
  spec/services/ad_renewal_letters_export_service_spec.rb
  spec/services/renewal_letters_bulk_pdf_service_spec.rb
Labels: enhancement

#384 Update env.example
  .env.example
Labels: enhancement

#388 Rename :generate namespace to :export
  config/schedule.rb
  lib/tasks/reports.rake
  spec/schedule_spec.rb
Labels: housekeeping

#386 Ad renewal letters - Create record first
  app/models/waste_exemptions_engine/ad_renewal_letters_export.rb
  app/services/ad_renewal_letters_export_service.rb
  db/migrate/20190912112625_add_status_to_ad_renewal_letters_export.rb
  db/schema.rb
  lib/tasks/ad_renewal_letters.rake
  lib/tasks/letters.rake
  spec/factories/ad_renewal_letters_export.rb
  spec/models/waste_exemptions_engine/ad_renewal_letters_export_spec.rb
  spec/services/ad_renewal_letters_export_service_spec.rb
Labels: enhancement

#390 Schedule export AD renewal letters
  .env.example
  .travis.yml
  config/schedule.rb
  spec/schedule_spec.rb
Labels: enhancement

#389 Add dashboard view to AD letters
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/partials/_letters.scss
  app/assets/stylesheets/partials/_links.scss
  app/assets/stylesheets/partials/_tags.scss
  app/controllers/ad_renewal_letters_exports_controller.rb
  app/controllers/letters_controller.rb
  app/models/ability.rb
  app/models/waste_exemptions_engine/ad_renewal_letters_export.rb
  app/presenters/ad_renewal_letters_export_presenter.rb
  app/views/ad_renewal_letters_exports/index.html.erb
  app/views/layouts/application.html.erb
  app/views/letters/index.html.erb
  config/initializers/time_formats.rb
  config/locales/ad_renewal_letters_exports.en.yml
  config/locales/en.yml
  config/locales/letters.en.yml
  config/routes.rb
  spec/factories/ad_renewal_letters_export.rb
  spec/models/waste_exemptions_engine/ad_renewal_letters_export_spec.rb
  spec/presenters/ad_renewal_letters_export_presenter_spec.rb
  spec/requests/ad_renewal_letters_exports_spec.rb
  spec/requests/letters_spec.rb
Labels: enhancement

#397 Cast string to integer
  lib/tasks/letters.rake
Labels: bug

#400 Clean old AD renewal letters files
  app/controllers/ad_renewal_letters_exports_controller.rb
  app/models/waste_exemptions_engine/ad_renewal_letters_export.rb
  app/services/ad_renewal_letters_export_cleaner_service.rb
  config/application.rb
  lib/tasks/letters.rake
  spec/models/waste_exemptions_engine/ad_renewal_letters_export_spec.rb
  spec/services/ad_renewal_letters_export_cleaner_service_spec.rb
Labels: enhancement

#403 Switch source of defra_ruby_aws to rubygems
  Gemfile
  Gemfile.lock
Labels: housekeeping

#405 Fix bug on Cleaning AD renewal letters
  lib/tasks/letters.rake
Labels: bug

#406 Add ordering to bulk AD renewal letters
  app/services/ad_renewal_letters_export_service.rb
Labels: enhancement

#407 Various fixes to AD letters
  app/helpers/ad_privacy_policy_helper.rb
  app/services/ad_renewal_letters_export_service.rb
  app/views/renewal_letter/_styles.html.erb
  app/views/renewal_letter/bulk.html.erb
Labels: bug

#408 Order exemptions correctly in the generated AD renewal letters
  app/presenters/renewal_letter_presenter.rb
Labels: bug

#410 Add visually hidden text for button
  app/assets/stylesheets/partials/_links.scss
  app/views/ad_renewal_letters_exports/index.html.erb
  config/locales/ad_renewal_letters_exports.en.yml
Labels: enhancement

#415 Add area lookup for addresses task
  .env.example
  .travis.yml
  Gemfile
  Gemfile.lock
  app/services/update_area_service.rb
  config/application.rb
  config/schedule.rb
  lib/tasks/lookups.rake
  spec/cassettes/ea_area_lookups_west_midlands.yml
  spec/lib/tasks/lookups_spec.rb
  spec/schedule_spec.rb
  spec/services/update_area_service_spec.rb
  spec/support/shared_examples/rake.rb
  spec/support/vcr.rb
Labels: enhancement

#426 Restrict missing area update job to site addresses
  lib/tasks/lookups.rake
  spec/lib/tasks/lookups_spec.rb
Labels: bug

#427 Housekeeping on the env vars
  .env.example
  config/application.rb
  config/initializers/waste_exemptions_engine.rb
  config/schedule.rb
  spec/presenters/reports/exemption_bulk_report_presenter_spec.rb
Labels: housekeeping

#428 Remove dependence on env vars for some tests
  .travis.yml
  spec/schedule_spec.rb
Labels: housekeeping

#429 Add support for rake integration tests
  lib/close_airbrake.rb
  lib/tasks/cleanup.rake
  lib/tasks/email.rake
  lib/tasks/expire_registration.rake
  lib/tasks/letters.rake
  lib/tasks/lookups.rake
  lib/tasks/reports.rake
  spec/lib/tasks/cleanup_spec.rb
  spec/lib/tasks/email_spec.rb
  spec/lib/tasks/expire_registration_spec.rb
  spec/lib/tasks/letters_spec.rb
  spec/lib/tasks/lookups_spec.rb
  spec/lib/tasks/one_off/reminders_spec.rb
  spec/lib/tasks/reports_spec.rb
  spec/support/rake_env.rb
  spec/support/shared_examples/rake.rb
  spec/support/simplecov.rb
Labels: housekeeping

#421 Add lookup job for X and Y updates on addresses
  app/services/update_easting_and_northing_service.rb
  config/application.rb
  config/schedule.rb
  lib/tasks/lookups.rake
  lib/timed_service_runner.rb
  spec/cassettes/invalid_postcode_lookup.yml
  spec/cassettes/valid_postcode_lookup.yml
  spec/lib/tasks/lookups_spec.rb
  spec/schedule_spec.rb
  spec/services/update_easting_and_northing_service_spec.rb
Labels: enhancement

#430 Update schedule.rb order by runtime
  config/schedule.rb
Labels: housekeeping
