Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2020-04, with the labels that each got.

#531 Update VCR cassettes
  spec/cassettes/valid_area_lookup.yml
  spec/cassettes/valid_postcode_lookup.yml
Labels: housekeeping

#535 Fix json dependency security issue
  Gemfile
  Gemfile.lock
Labels: dependencies, security

#536 Refresh VCR cassettes
  spec/cassettes/valid_area_lookup.yml
  spec/cassettes/valid_postcode_lookup.yml
Labels: housekeeping

#538 Fix SonarCloud code coverage reporting
  Gemfile
  Gemfile.lock
Labels: bug

#540 Use multiple rubocop formats in Travis build
  .travis.yml
Labels: housekeeping

#544 Don't expire VCR cassettes
  spec/support/vcr.rb
Labels: housekeeping
