Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2020-07, with the labels that each got.

#574 Changes need to support switch to 'main' branch
  Gemfile
  Gemfile.lock
  README.md
Labels: housekeeping

#579 Update defra-ruby-aws to encryption configurable
  Gemfile.lock
  config/initializers/defra_ruby_aws.rb
Labels: enhancement

#580 Update defra-ruby-alert
  Gemfile.lock
Labels: housekeeping

#581 Revert "Update defra-ruby-alert"
  Gemfile.lock
Labels: housekeeping

#585 Fix wrong letter cleanup service called
  lib/tasks/letters.rake
Labels: bug

#586 Change AD confirm. letters job start time
  config/schedule.rb
  spec/schedule_spec.rb
Labels: housekeeping

#587 Update whenever to latest
  Gemfile
  Gemfile.lock
Labels: housekeeping

#590 Add developer role to back-office
  app/models/.keep
  app/models/ability.rb
  app/models/user.rb
  config/locales/en.yml
  config/locales/user_roles.en.yml
  config/locales/users.en.yml
  db/schema.rb
  db/seeds/users.json
  spec/factories/user.rb
  spec/models/ability_spec.rb
Labels: enhancement

#591 Refactor how can? is stubbed in some tests
  spec/helpers/action_links_helper_spec.rb
Labels: housekeeping

#573 Integrate defra-ruby-features engine
  Gemfile
  Gemfile.lock
  app/models/ability.rb
  app/views/layouts/application.html.erb
  config/application.rb
  config/initializers/defra_ruby_features.rb
  config/locales/en.yml
  config/routes.rb
  spec/models/ability_spec.rb
  spec/support/shared_examples/abilities/developer_examples.rb
Labels: enhancement
