Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2022-08, with the labels that each got.

#884 Send letters to contacts with no email address
  app/controllers/resend_confirmation_email_controller.rb
  app/models/waste_exemptions_engine/registration.rb
  app/services/bulk_notify_renewal_letters_service.rb
  app/services/remove_nccc_email_service.rb
  app/services/renewal_reminder_service_base.rb
  lib/tasks/one_off/remove_nccc_email.rake
  spec/factories/registration.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/requests/resend_confirmation_email_spec.rb
  spec/services/bulk_notify_renewal_letters_service_spec.rb
  spec/services/first_renewal_reminder_service_spec.rb
  spec/services/remove_nccc_email_service_spec.rb
  spec/services/second_renewal_reminder_service_spec.rb
Labels: enhancement

#903 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#904 Add renewals column to boxi exemptions export
  app/models/reports/boxi/registration_exemptions_serializer.rb
  app/models/waste_exemptions_engine/registration_exemption.rb
  spec/models/registration_exemption_spec.rb
  spec/models/reports/boxi/registration_exemptions_serializer_spec.rb
Labels: enhancement

#911 Adding telephone to the search criteria
  app/models/concerns/can_be_searched_like_registration.rb
  app/models/concerns/can_be_searched_like_telephone.rb
  app/models/waste_exemptions_engine/new_registration.rb
  app/models/waste_exemptions_engine/registration.rb
  config/locales/dashboards.en.yml
  spec/factories/new_registration.rb
  spec/models/new_registration_spec.rb
  spec/models/waste_exemptions_engine/registration_spec.rb
  spec/services/search_service_spec.rb
  spec/support/shared_examples/searching_phone_number_attribute.rb
Labels: enhancement

#914 Fix search issue
  app/models/concerns/can_be_searched_like_telephone.rb
  spec/factories/new_registration.rb
  spec/factories/registration.rb
  spec/services/search_service_spec.rb
Labels: bug
