Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2023-09, with the labels that each got.

#1126 Feature/ruby 2641 wex communication history showing in back office
  app/controllers/communication_logs_controller.rb
  app/helpers/action_links_helper.rb
  app/views/communication_logs/index.html.erb
  app/views/shared/_resource_details.html.erb
  config/initializers/time_formats.rb
  config/locales/communication_logs.en.yml
  config/locales/partials/resource_details.en.yml
  config/routes.rb
  spec/factories/communication_log.rb
  spec/factories/registration_communication_log.rb
  spec/requests/communication_logs_spec.rb
Labels: enhancement

#1138 Feature/edit forms
  app/controllers/testing_controller.rb
  app/views/testing/show.html.erb
Labels: housekeeping

#1140 Fix typo in I18n key
  Gemfile.lock
  app/presenters/notify_renewal_letter_presenter.rb
Labels: bug

#1148 Fix/self serve edit issues
  Gemfile.lock
  app/controllers/deregistration_email_exports_controller.rb
  app/controllers/resend_deregistration_emails_controller.rb
  app/controllers/send_edit_invite_emails_controller.rb
  app/controllers/users_controller.rb
  app/forms/deregistration_email_exports_form.rb
  app/helpers/action_links_helper.rb
  app/jobs/send_deregistration_email_job.rb
  app/models/ability.rb
  app/models/reports/deregistration_email_batch_serializer.rb
  app/services/deregistration_email_service.rb
  app/services/reports/deregistration_email_batch_export_service.rb
  app/services/resend_deregistration_email_service.rb
  app/views/layouts/application.html.erb
  app/views/shared/_resource_details.html.erb
  config/environments/development.rb
  config/locales/partials/resource_details.en.yml
  config/locales/resend_deregistration_emails.en.yml
  config/locales/send_edit_invite_emails.en.yml
  config/routes.rb
  lib/tasks/email.rake
  spec/features/dashboard_spec.rb
  spec/helpers/action_links_helper_spec.rb
  spec/jobs/send_deregistration_email_job_spec.rb
  spec/lib/tasks/lookups_spec.rb
  spec/models/reports/deregistration_email_batch_serializer_spec.rb
  spec/models/user_spec.rb
  spec/models/waste_exemptions_engine/registration_exemption_spec.rb
  spec/requests/deregistration_email_export_spec.rb
  spec/requests/resend_confirmation_email_spec.rb
  spec/requests/resend_confirmation_letter_spec.rb
  spec/requests/resend_deregistration_emails_spec.rb
  spec/requests/resend_renewal_email_spec.rb
  spec/requests/resend_renewal_letter_spec.rb
  spec/requests/send_edit_invite_email_spec.rb
  spec/requests/user_roles_spec.rb
  spec/services/deregistration_email_service_spec.rb
  spec/services/deregistration_service_spec.rb
  spec/services/expired_registration_cleanup_service_spec.rb
  spec/services/reports/deregistration_email_batch_export_service_spec.rb
  spec/services/resend_deregistration_email_service_spec.rb
  spec/support/shared_examples/abilities/developer_examples.rb
Labels: enhancement
