Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2023-06, with the labels that each got.

#1079 Upgrade to Rails 7
  .ruby-version
  Gemfile
  Gemfile.lock
  README.md
  app/assets/config/manifest.js
  app/presenters/bulk_exports_presenter.rb
  app/presenters/notify_renewal_letter_presenter.rb
  app/presenters/reports/exemption_bulk_report_presenter.rb
  app/presenters/reports/exemption_epr_report_presenter.rb
  app/services/renewal_reminder_email_service.rb
  app/services/reports/monthly_bulk_report_service.rb
  config/application.rb
  db/schema.rb
Labels: housekeeping

#1080 Modify uglifier instantiation to support ES6
  config/environments/production.rb
Labels: housekeeping

#1084 Feature/ruby 2514 edit expiry date
  app/controllers/modify_expiry_date_controller.rb
  app/forms/modify_expiry_date_form.rb
  app/helpers/action_links_helper.rb
  app/models/ability.rb
  app/views/modify_expiry_date/new.html.erb
  app/views/shared/_resource_details.html.erb
  config/locales/forms/modify_expiry_date.en.yml
  config/locales/partials/resource_details.en.yml
  config/routes.rb
  spec/factories/forms/modify_expiry_date_form.rb
  spec/forms/modify_expiry_date_form_spec.rb
  spec/helpers/action_links_helper_spec.rb
  spec/requests/modify_expiry_date_spec.rb
  spec/services/deregistration_email_service_spec.rb
  spec/support/shared_examples/abilities/below_super_agent_examples.rb
  spec/support/shared_examples/abilities/super_agent_examples.rb
Labels: enhancement

#1087 Fix/action links helper
  app/helpers/action_links_helper.rb
  spec/forms/modify_expiry_date_form_spec.rb
  spec/helpers/action_links_helper_spec.rb
Labels: bug

#1089 Feature/ruby 2455 wex notify text messaging renewal reminder texts
  .rubocop_todo.yml
  Gemfile.lock
  app/models/waste_exemptions_engine/registration.rb
  app/services/final_renewal_reminder_service.rb
  app/services/final_renewal_reminder_text_service.rb
  app/services/renewal_reminder_email_service.rb
  app/services/renewal_reminder_service.rb
  app/services/renewal_reminder_text_service.rb
  app/services/renewal_reminder_text_service_base.rb
  config/application.rb
  config/feature_toggles.yml
  config/schedule.rb
  lib/tasks/text.rake
  spec/factories/registration.rb
  spec/schedule_spec.rb
  spec/services/final_renewal_reminder_service_spec.rb
  spec/services/renewal_reminder_text_service_spec.rb
Labels: enhancement

#1095 Update CHANGELOG
  CHANGELOG.md
  Gemfile.lock
Labels: housekeeping
