Repository DEFRA/waste-exemptions-back-office, pull requests merged in 2023-10, with the labels that each got.

#1154 Fix/ruby 2481 comms history
  app/views/communication_logs/index.html.erb
  lib/tasks/one_off/move_deregistration_email_sent_at_to_communication_logs.rake
  spec/lib/tasks/one_off/move_deregistration_email_sent_at_to_communication_logs_spec.rb
Labels: bug

#1162 Update CHANGELOG
  CHANGELOG.md
Labels: housekeeping

#1168 Rake task to rename site_address areas
  Gemfile.lock
  lib/fixtures/area_names_20231011.csv
  lib/tasks/one_off/rename_site_location_areas.rake
  spec/lib/tasks/one_off/rename_site_location_areas_spec.rb
Labels: enhancement
